### ISSUE TITLE
Implement graph in filter options

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#139]
## Description: 

Please see https://github.com/mlibrary/fishrappr/issues/115 for investigation ticket

## Acceptance Criteria:

- [x] Display decade level graph
- [x] Abiility to further filter to year-level graph
- [x] Ability to further filter to Month-level graph
- [x] users must be able to tab through results numbers (accessibility)
- [x] label the axes
- [x] look into scaling the divisions

**Comment by gordonleacock** [comment]
I added the ability to filter to date-in-month graph. Right now the ability to click on a bar to zoom to the next level down (e.g., year -- > month) isn't working. But changing the date facet selections changes the graph appropriately.  You can tab through the results inside the graph but I'm not sure what screen readers will hear.

**Comment by gordonleacock** [comment]
The axis information is display below the graph at this point because I didn't want to make the graph any wider. Currently no markers for bar width or scale. Hovering on a bar displays search page count for that time unit. Zooming in on bar data by clicking a bar is working. Graph adjusts as the user changes filters. Tabbing inside the graph works but we need to test what screen readers articulate.

So, I think version one of the graph is completed. I should add that the whole fishrappr option section of the page is not responsive. I'd like to discuss this at the stand up meeting.

**Comment by gordonleacock** [comment]
I think any additional work should be a new issue at this point.

**Comment by kaylaondracek** [comment]
Hi Gordon - were you able to address the responsiveness of the graph section?

**Comment by gordonleacock** [comment]
I'd like to put that into a separate issue for the next sprint after we
review and discuss the current version, which we can do once staging is up
and running. Unless I find time to work on it today and tomorrow morning.
:-)

**Comment by kaylaondracek** [comment]
Works for me! I was just curious 👍
