### ISSUE TITLE
Should "Sort by Page Number" be "Sort by Page Sequence"?

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#229]
## Description: 

The app is *technically* not sorting by page number, but sequence.

## Acceptance Criteria:

- [x] people who know data are not irked

**Comment by gordonleacock** [comment]
Not so user friendly???
Sort by Page Image Number (since we name them images in search result).

It seems that when the sort by date bug (image one shows up at the end of the sequence) is fixed that we could do away with "Sort by Page Number" altogether because it will be the same as sort by date.  Or am I wrong. ;-)

**Comment by respinos** [comment]
There is no bug; the old link wasn't setting up a sorted query, but it does now. Since viewing an issue is the same thing as invoking a search, I don't think we have an option of tweaking the UI to be different for this use case.

Sort by Image Number would work. We can ditch the "Page".

**Comment by respinos** [comment]
"Sort by Page Number" has been removed.
Added "Sort by Interesting" (Relevance) to the configuration, and that's the default.
