### ISSUE TITLE
Add comment "Something wrong  with this page? Report it"

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#249]
## Description:

On page view, add the comment  "Something wrong  with this page? Report it". Link it to Contact Us page. 
## Acceptance Criteria:
- [x] 'Report a Problem' link appears on the page
- [x] 'Report a Problem' is linked to Contact Us form
- [x] Add "Report a Problem" to bottom of page sidebar

**Comment by bnhowell** [comment]
@njaffer Will this report the URL as well?

**Comment by respinos** [comment]
Where is this comment to be located? (This project sure _loves_ its super verbose labels :-)

**Comment by njaffer** [comment]
@bnhowell: That was our understanding. Thoughts? @respinos @gordonleacock

**Comment by respinos** [comment]
Yes, the URL will be reported.

**Comment by respinos** [comment]
Trying to grok if this ticket refers to a *second* link (not image, but content --- because we have options for that on the contact form.

Option 1:

![image](https://cloud.githubusercontent.com/assets/537867/19727617/20a11236-9b5e-11e6-8e7f-16a4bec00960.png)

Option 2:

![image](https://cloud.githubusercontent.com/assets/537867/19727767/c30f8eb2-9b5e-11e6-825a-0aae90c23cc9.png)

Option 3:

![image](https://cloud.githubusercontent.com/assets/537867/19727830/05668aea-9b5f-11e6-8069-c6541ddbc98c.png)

Option 2 and 3 suggest we could put a similar link on the search pages.

**Comment by Treevore** [comment]
Option 1 for sure. I think if we did a button it would have to be a different color, or even styling. Right now all those feature some sort of control on linking or downloading what you are seeing.

Maybe for Option 2 & 3 it could be just text styling, but in similar locations, I'll upload some images on this ticket.

**Comment by Treevore** [comment]
![screen shot 2016-10-26 at 10 44 17 am](https://cloud.githubusercontent.com/assets/502199/19730759/346e35b8-9b69-11e6-8aa0-2d038464441d.png)

Here's something without an icon, to draw less attention to it (if needed).

**Comment by respinos** [comment]
Your Option 4 can even more readily be adapted to other pages (like search results) if we wanted to.

**Comment by bnhowell** [comment]
I'm sorry for responding late to this. I liked option 1 but without a
second line.

Something like:
"(Statement about OCR errors) Read more about OCR quality or Report a
problem"
