### ISSUE TITLE
About & Help Page Fixes

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#263]
## Description:
- typos in menu ("Archives")
- fix `/about` link to resolve (redirect? change?)
- fix about (other static?) `<title>` elements
- RIghts Statement should route to contact form
## Acceptance Criteria:
- [x] links from home page are successful
- [x] `<title>` should not have translation issues

**Comment by respinos** [comment]
@gordonleacock - when you link to contact form, use `contacts_path type: 'permissions'`, so the permissions option is selected when they follow that link.

**Comment by gordonleacock** [comment]
I've left this so "About the Archives" goes to About The Michigan Daily because I think that's what our sponsors would like. We may need to change the labeling and perhaps add a link about the project.

**Comment by Treevore** [comment]
![screen shot 2016-11-10 at 10 09 04 am](https://cloud.githubusercontent.com/assets/502199/20181897/ef584f60-a72d-11e6-9591-d135256a026d.png)

Here's an image for the Image Viewer help page (as a reference image)

I realized this is probably not the right size since I'm using a mockup and not current development dimensions. Would it be better to screenshot a picture of the staging?

**Comment by respinos** [comment]
Looks close to me --- honestly the only thing that's "off" is that "Pan"
isn't selected.

-R

**Comment by Treevore** [comment]
![viewer default](https://cloud.githubusercontent.com/assets/502199/20182371/8bd3de8a-a72f-11e6-9a53-45a136df0b33.png)
