### ISSUE TITLE
Add help text for 'Download Current View'

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#279]
## Description: 
The help page does not have help text for 'download current view'
<img width="728" alt="screen shot 2016-12-02 at 9 44 42 am" src="https://cloud.githubusercontent.com/assets/12487929/20838077/f7f80c48-b874-11e6-8716-8e2e25fd7798.png">

## Acceptance Criteria:

- [ ] 
- [ ]

**Comment by bnhowell** [comment]
Reordered help content to follow the order of elements in the image viewer. Added 'download current view' and 'Reset Viewer' content. Deleted 'Pan' content (pan viewer was removed from interface.
Related Ticket: #273 

Updated content below:

### Image viewer tools 

To help you interact with the images in the Michigan Daily Digital Archive we created a number of tools for you to use. 

**Zoom In / Zoom Out** - Increase or decrease the size of the page image within the viewer.
**Reset Viewer** - Return image to default size
**Rotate the Image** - Rotate the image 90 degrees. This is helpful when you encounter a page that is upside down or on its side due to a digitization error. 
**Select** - Select to click-and-drag a box around a section of the image. You can then download only the selected section, zoom in further on that section or cancel and return to the full image viewer. 
**Search Keyword Highlights** - Toggle the check box to see your search term(s) highlighted within the image. Hit highlighting also appears within the plain text below the image. 
**Report a Problem Link** - Indicates the page you’re on along with your comment - this helps us troubleshoot!
**Download Current View** - Download a high-resolution image of the current newspaper section that appears in the image viewer.
